### ISSUE TITLE
awss_start is not built in the libiot_sdk.a in iotkit version 2.3.0

### ISSUE THREAD

**Issue by pansila** [RT-Thread-packages/ali-iotkit#11]
A message showed that linker can't find the symbol awss_start when I comment out FEATURE_WIFI_PROVISION_ENABLED=y in the make.settings, I searched it in the libiot_sdk.a and there is indeed no such symbol in the library. If I uncomment the feature, namely keep it enabled, the symbol is back and build works fine.

Please help to check whether it's expected as WIFI_PROVISION is supposed to be an independent feature out of all cloud services.

**Comment by hellozimo** [comment]
ali-iotkit 这个仓库是经过修改后的非官方仓库，使用了 Scons 进行重新构建，而非官方的 make 构建。另外，此仓库中的软件包不需要编译成库文件进行链接。

**Comment by pansila** [comment]
Thanks, I posted it the wrong place
